#ifndef _HW_H_
#define _HW_H_
/**
 * Board level definitions of the hardware and various pins/peripherals
 * Elliot Buller 2012
 **/

// Include core avr headers
#include <avr/io.h>
#include <util/delay.h>
#include <avr/pgmspace.h>

// Tried to recursively define preprocessors but gcc preproc doesn't like
// that. ;( Instead we preprocess pins.h in perl to produce pins_auto.h
//#define PIN_DEFINE(name,port,pin)      #define name##_PORT PORT##port
//                                       #define name##_PIN  _BV(pin)
//                                       #define name##_DIR  DDR##port
				     
// Pin definitions
// DON'T EDIT pins_auto.h or include it in any file!! 
// It is autogenerated, instead change pins.h and rerun 
// process_pins.pl or make.
#include "pins_auto.h"

// Pin accessors
#define OUTPUT(name)                 name##_DIR  |= name##_PIN
#define INPUT(name)                  name##_DIR  &= ~name##_PIN
#define HIGH(name)                   name##_PORT |= name##_PIN
#define LOW(name)                    name##_PORT &= ~name##_PIN
#define TOGGLE(name)                 name##_PORT ^= name##_PIN
#define READ(name)                   (name##_IN  & name##_PIN)

#endif /* _HW_H_ */
