#define lcd_dc_PORT	PORTB
#define lcd_dc_PIN	_BV(0)
#define lcd_dc_DIR	DDRB
#define lcd_dc_IN	PINB
#define spi_sck_PORT	PORTB
#define spi_sck_PIN	_BV(1)
#define spi_sck_DIR	DDRB
#define spi_sck_IN	PINB
#define spi_mosi_PORT	PORTB
#define spi_mosi_PIN	_BV(2)
#define spi_mosi_DIR	DDRB
#define spi_mosi_IN	PINB
#define spi_miso_PORT	PORTB
#define spi_miso_PIN	_BV(3)
#define spi_miso_DIR	DDRB
#define spi_miso_IN	PINB
#define rf_irq_PORT	PORTB
#define rf_irq_PIN	_BV(4)
#define rf_irq_DIR	DDRB
#define rf_irq_IN	PINB
#define rf_gpio_PORT	PORTB
#define rf_gpio_PIN	_BV(5)
#define rf_gpio_DIR	DDRB
#define rf_gpio_IN	PINB
#define _spare_PORT	PORTB
#define _spare_PIN	_BV(6)
#define _spare_DIR	DDRB
#define _spare_IN	PINB
#define lcd_rst_PORT	PORTB
#define lcd_rst_PIN	_BV(7)
#define lcd_rst_DIR	DDRB
#define lcd_rst_IN	PINB
#define usb_i_sel_PORT	PORTC
#define usb_i_sel_PIN	_BV(6)
#define usb_i_sel_DIR	DDRC
#define usb_i_sel_IN	PINC
#define pshold_PORT	PORTC
#define pshold_PIN	_BV(7)
#define pshold_DIR	DDRC
#define pshold_IN	PINC
#define scl_PORT	PORTD
#define scl_PIN	_BV(0)
#define scl_DIR	DDRD
#define scl_IN	PIND
#define sda_PORT	PORTD
#define sda_PIN	_BV(1)
#define sda_DIR	DDRD
#define sda_IN	PIND
#define rx_PORT	PORTD
#define rx_PIN	_BV(2)
#define rx_DIR	DDRD
#define rx_IN	PIND
#define tx_PORT	PORTD
#define tx_PIN	_BV(3)
#define tx_DIR	DDRD
#define tx_IN	PIND
#define rf_cs_PORT	PORTD
#define rf_cs_PIN	_BV(4)
#define rf_cs_DIR	DDRD
#define rf_cs_IN	PIND
#define xck_PORT	PORTD
#define xck_PIN	_BV(5)
#define xck_DIR	DDRD
#define xck_IN	PIND
#define rf_sdn_PORT	PORTD
#define rf_sdn_PIN	_BV(6)
#define rf_sdn_DIR	DDRD
#define rf_sdn_IN	PIND
#define lcd_cs_PORT	PORTD
#define lcd_cs_PIN	_BV(7)
#define lcd_cs_DIR	DDRD
#define lcd_cs_IN	PIND
#define hwb_PORT	PORTE
#define hwb_PIN	_BV(2)
#define hwb_DIR	DDRE
#define hwb_IN	PINE
#define sd_det_PORT	PORTE
#define sd_det_PIN	_BV(6)
#define sd_det_DIR	DDRE
#define sd_det_IN	PINE
#define led_PORT	PORTF
#define led_PIN	_BV(0)
#define led_DIR	DDRF
#define led_IN	PINF
#define sd_cs_PORT	PORTF
#define sd_cs_PIN	_BV(1)
#define sd_cs_DIR	DDRF
#define sd_cs_IN	PINF
#define sd_pwr_PORT	PORTF
#define sd_pwr_PIN	_BV(4)
#define sd_pwr_DIR	DDRF
#define sd_pwr_IN	PINF
#define btn1_PORT	PORTF
#define btn1_PIN	_BV(5)
#define btn1_DIR	DDRF
#define btn1_IN	PINF
#define btn2_PORT	PORTF
#define btn2_PIN	_BV(6)
#define btn2_DIR	DDRF
#define btn2_IN	PINF
#define vbatt_PORT	PORTF
#define vbatt_PIN	_BV(7)
#define vbatt_DIR	DDRF
#define vbatt_IN	PINF
